.\obj\ethernetdriver.o: src\EthernetDriver\EthernetDriver.c
.\obj\ethernetdriver.o: .\inc\opora.h
.\obj\ethernetdriver.o: .\inc\core_cm1.h
.\obj\ethernetdriver.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stdint.h
.\obj\ethernetdriver.o: .\inc\opora_can_defs.h
.\obj\ethernetdriver.o: .\inc\opora_usb_defs.h
.\obj\ethernetdriver.o: .\inc\opora_eeprom_defs.h
.\obj\ethernetdriver.o: .\inc\opora_rst_clk_defs.h
.\obj\ethernetdriver.o: .\inc\opora_dma_defs.h
.\obj\ethernetdriver.o: .\inc\opora_uart_defs.h
.\obj\ethernetdriver.o: .\inc\opora_spi_defs.h
.\obj\ethernetdriver.o: .\inc\opora_mil_std_1553_defs.h
.\obj\ethernetdriver.o: .\inc\opora_power_defs.h
.\obj\ethernetdriver.o: .\inc\opora_wwdg_defs.h
.\obj\ethernetdriver.o: .\inc\opora_iwdg_defs.h
.\obj\ethernetdriver.o: .\inc\opora_timer_defs.h
.\obj\ethernetdriver.o: .\inc\opora_adc_defs.h
.\obj\ethernetdriver.o: .\inc\opora_dac_defs.h
.\obj\ethernetdriver.o: .\inc\opora_port_defs.h
.\obj\ethernetdriver.o: .\inc\opora_arinc429r_defs.h
.\obj\ethernetdriver.o: .\inc\opora_bkp_defs.h
.\obj\ethernetdriver.o: .\inc\opora_arinc429t_defs.h
.\obj\ethernetdriver.o: .\inc\opora_ext_bus_cntrl_defs.h
.\obj\ethernetdriver.o: .\inc\opora_ethernet_defs.h
.\obj\ethernetdriver.o: .\inc\opora_sys_defs.h
.\obj\ethernetdriver.o: src\EthernetDriver\EthernetDriver.h
.\obj\ethernetdriver.o: .\inc\config.h
.\obj\ethernetdriver.o: src\EthernetDriver\1. Options for EthernetDriver.c
